In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Student-Performance-csv_T4qDx.csv")

In [3]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [4]:
df.tail()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [5]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [6]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [7]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [9]:
df["Extracurricular Activities"]

0       Yes
1        No
2       Yes
3       Yes
4        No
       ...
9995    Yes
9996    Yes
9997    Yes
9998    Yes
9999     No
Name: Extracurricular Activities, Length: 10000, dtype: object

In [12]:
le=LabelEncoder()
df["Extracurricular Activities"]=le.fit_transform(df["Extracurricular Activities"])

In [13]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [17]:
x = df[["Hours Studied","Previous Scores","Extracurricular Activities","Sleep Hours","Sample Question Papers Practiced"]]

In [18]:
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [20]:
y=df["Performance Index"]

In [21]:
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test,y_train, y_test=train_test_split(x,y,test_size=.2)

In [24]:
x_train

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
8995,9,98,1,9,1
2457,9,91,0,5,2
3684,4,45,1,4,8
5648,8,94,0,8,6
6160,6,44,0,6,3
...,...,...,...,...,...
5737,8,41,1,5,0
6015,3,78,1,4,2
7473,8,78,1,7,6
1031,1,46,0,6,6
229,4,82,1,8,4

In [25]:
x_test

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
2096,9,56,1,5,9
8265,1,58,0,8,6
7300,6,56,0,6,7
1244,4,49,1,7,0
7694,4,82,1,6,4
...,...,...,...,...,...
8552,2,58,0,9,7
6156,4,79,0,5,2
190,3,65,0,7,8
6618,5,75,1,4,0
3688,8,90,1,7,3

In [27]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)

In [28]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [29]:
model=LinearRegression()
model.fit(x_train_scaled,y_train)

LinearRegression()

In [34]:
y_pred=model.predict(x_test_scaled)

In [35]:
x_test_scaled

array([[ 1.57939946, -0.76165291,  1.00400803, -0.92396408,  1.52608441],
       [-1.55744157, -0.64552958, -0.99600797,  0.82541568,  0.49156781],
       [ 0.40308407, -0.76165291, -0.99600797, -0.34083749,  0.83640667],
       ...,
       [-0.77323131, -0.23909793, -0.99600797,  0.2422891 ,  1.18124554],
       [ 0.01097894,  0.34151871,  1.00400803, -1.50709066, -1.5774654 ],
       [ 1.18729433,  1.21244367,  1.00400803,  0.2422891 , -0.5429488 ]])

In [36]:
model.predict([[1.57939946, -0.76165291,  1.00400803, -0.92396408,  1.52608441]])

array([53.91926111])

In [37]:
mean_squared_error(y_test, y_pred)

4.330426163224613

In [38]:
r2_score(y_test,y_pred)

0.9883847596722526

In [ ]:
import pickle
with open("student_lr_final_model.pkl",'wb') as file:
    pickle.dump((model,scaler,le),file)